# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hooked on a feeling
email: christelle.lyn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  She lives the poetry she cannot write. Crazy for turtles, sushi and the spontaneity of life.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: telleeehhh
facebook_username:  thepatronus
permalink: none

# Build settings
markdown: kramdown
